In [1]:
import pandas as pd

In [ ]:
orders = pd.read_csv('orders_cleaned.csv')

# dates(yyyy-mm-dd)

In [ ]:
orders['order_date'] = pd.to_datetime(orders['order_date'],format='%Y-%m-%d').dt.strftime('%Y-%m-%d')
orders['required_date'] = pd.to_datetime(orders['required_date'],format='%Y-%m-%d').dt.strftime('%Y-%m-%d')
orders['shipped_date'] = pd.to_datetime(orders['shipped_date'],format='%Y-%m-%d', errors = 'coerce').dt.strftime('%Y-%m-%d')
orders['shipped_date'] = orders['shipped_date'].fillna('')
print("Dates converted successfully")

Dates converted successfully

In [ ]:
orders.head(5)

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6

In [ ]:
orders.to_csv('orders_cleaned(1).csv',index=False)

In [ ]:
orders['shipped_date'] = orders['shipped_date'].replace([' ','','NULL','NA','N/A'],pd.NaT)
orders ['shipped_date'] = pd.to_datetime(orders['shipped_date'],errors = 'coerce')

In [ ]:
orders['shipped_date'].dtype

dtype('<M8[ns]')

In [ ]:
orders['shipped_date'] = pd.to_datetime(orders['shipped_date'], errors='coerce').dt.date
orders['order_date'] = pd.to_datetime(orders['order_date']).dt.date
orders['required_date'] = pd.to_datetime(orders['required_date']).dt.date

In [ ]:
orders[['shipped_date']].head()

  shipped_date
0   2016-01-03
1   2016-01-03
2   2016-01-03
3   2016-01-05
4   2016-01-06

In [ ]:
orders.to_csv('orders_clean.csv',index=False)

In [2]:
orders = pd.read_csv('orders_cleann.csv')

In [3]:
orders['shipped_date'] = orders['shipped_date'].replace(r'^\s*$',pd.NA, regex=True)
orders['shipped_date'] = pd.to_datetime(orders['shipped_date'],errors='coerce').dt.date

In [5]:
orders.iloc[1445]

order_id               1446
customer_id             820
order_status              4
order_date       2018-03-17
required_date    2018-03-18
shipped_date     2018-03-18
store_id                  2
staff_id                  6
Name: 1445, dtype: object

In [6]:
repr(orders['shipped_date'][1445])

'datetime.date(2018, 3, 18)'

In [7]:
orders['shipped_date'] = pd.to_datetime(
    orders['shipped_date'],
    errors='coerce'
)

orders['shipped_date'] = orders['shipped_date'].where(
    orders['shipped_date'].notnull(),
    None
)

In [9]:
orders['order_date'] = pd.to_datetime(orders['order_date']).dt.strftime('%Y-%m-%d')

orders['required_date'] = pd.to_datetime(orders['required_date']).dt.strftime('%Y-%m-%d')

orders['shipped_date'] = pd.to_datetime(
    orders['shipped_date'],
    errors='coerce'
).dt.strftime('%Y-%m-%d')

In [10]:
orders = orders.fillna('')

In [13]:
orders.iloc[1445]
orders.iloc[1445].to_dict()

{'order_id': 1446,
 'customer_id': 820,
 'order_status': 4,
 'order_date': '2018-03-17',
 'required_date': '2018-03-18',
 'shipped_date': '2018-03-18',
 'store_id': 2,
 'staff_id': 6}

In [15]:
import csv

orders.to_csv('clean_orders.csv',index=False,quoting=csv.QUOTE_ALL)